# Generated by Django 5.0.1 on 2024-01-22 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Userdetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("checkbox", models.CharField(max_length=100)),
            ],
            options={"db_table": "userinfo",},
        ),
        migrations.CreateModel(
            name="UserVastdetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=255)),
                ("lname", models.CharField(max_length=255)),
                ("username", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=100)),
                ("checkbox", models.CharField(max_length=100)),
            ],
            options={"db_table": "user_vast_info",},
        ),
    ]
